### ISSUE TITLE
Requirements File

### ISSUE THREAD

**Issue by frozenWaffles123** [range-et/BumbleBot#1]
Hi,

I'm unable to perform a pip install of the dependencies. Could you update the requirements file so that its pointing to the correct dependency versions? Also, looks like there is a typo in the filename.

Thanks in advance!

**Comment by range-et** [comment]
Hey! Thanks for letting me know - I am not sure why you are getting this error but I looked into it and it would appear that some of the requirements were being installed from my cached files. Maybe try like an install of :
`pipenv install tensorflow selenium pandas scikit-image scikit-learn`
